scalar Date

type User {
    id: ID,
    name: String,
    email: String,
    password: String,
    created_at: Date,
    updated_at: Date,
}

input UserInput {
    name: String,
    email: String,
    password: String,
}

type Query {
    getAllUsers: [User],
}

type Mutation {
    createUser(input: UserInput): User,
}